### ISSUE TITLE
Suggest

### ISSUE THREAD

**Issue by rageyh** [xSehrMotiviert/velocityplus#15]
Add the /hub command

**Comment by xSehrMotiviert** [comment]
VelocityPlus was never intended to have such a command.

The idea behind it was to be able to use the standard BungeeCord commands in Velocity to make the user experience a little easier for everyone switching from BungeeCord to Velocity.


I'll be happy to add it to my own to-do list, but it's not currently a priority as I have more than enough to do with my current projects besides work.

Maybe someone else can get involved in the project and follow up on the request.

Translated with www.DeepL.com/Translator (free version)

**Comment by xSehrMotiviert** [comment]
I'm closing this issue for now. I still keep this in mind, but as I said. It's not what I wanted velocityplus to have.
